import {
    AdFlag,
    AfFlag,
    AgFlag,
    AiFlag,
    AlFlag,
    AmFlag,
    AoFlag,
    ArFlag,
    AtFlag,
    AuFlag,
    AwFlag,
    AxFlag,
    AzFlag,
    BaFlag,
    BbFlag,
    BdFlag,
    BeFlag,
    BfFlag,
    BgFlag,
    BhFlag,
    BiFlag,
    BjFlag,
    BmFlag,
    BnFlag,
    BoFlag,
    BrFlag,
    BsFlag,
    BtFlag,
    BwFlag,
    ByFlag,
    BzFlag,
    CaFlag,
    CatFlag,
    CdFlag,
    CfFlag,
    CgFlag,
    CiFlag,
    ClFlag,
    CnFlag,
    CoFlag,
    CrFlag,
    CuFlag,
    CvFlag,
    CyFlag,
    CzFlag,
    DjFlag,
    DkFlag,
    DmFlag,
    DoFlag,
    DzFlag,
    HrFlag,
    KhFlag,
    KmFlag,
    KyFlag,
    TdFlag,
} from "./flags";
import { SVGRProps } from "./types";

export const countries = [
    {
        name: "Afghanistan",
        dial_code: "+93",
        code: "AF",
        flag: AfFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Aland Islands",
        dial_code: "+358",
        code: "AX",
        flag: AxFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Albania",
        dial_code: "+355",
        code: "AL",
        flag: AlFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Algeria",
        dial_code: "+213",
        code: "DZ",
        flag: DzFlag as React.ComponentType<SVGRProps>,
    },

    {
        name: "Andorra",
        dial_code: "+376",
        code: "AD",
        flag: AdFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Angola",
        dial_code: "+244",
        code: "AO",
        flag: AoFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Anguilla",
        dial_code: "+1264",
        code: "AI",
        flag: AiFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Antarctica",
        dial_code: "+672",
        code: "AQ",
        flag: AqFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Antigua and Barbuda",
        dial_code: "+1268",
        code: "AG",
        flag: AgFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Argentina",
        dial_code: "+54",
        code: "AR",
        flag: ArFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Armenia",
        dial_code: "+374",
        code: "AM",
        flag: AmFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Aruba",
        dial_code: "+297",
        code: "AW",
        flag: AwFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Australia",
        dial_code: "+61",
        code: "AU",
        flag: AuFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Austria",
        dial_code: "+43",
        code: "AT",
        flag: AtFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Azerbaijan",
        dial_code: "+994",
        code: "AZ",
        flag: AzFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Bahamas",
        dial_code: "+1242",
        code: "BS",
        flag: BsFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Bahrain",
        dial_code: "+973",
        code: "BH",
        flag: BhFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Bangladesh",
        dial_code: "+880",
        code: "BD",
        flag: BdFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Barbados",
        dial_code: "+1246",
        code: "BB",
        flag: BbFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Belarus",
        dial_code: "+375",
        code: "BY",
        flag: ByFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Belgium",
        dial_code: "+32",
        code: "BE",
        flag: BeFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Belize",
        dial_code: "+501",
        code: "BZ",
        flag: BzFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Benin",
        dial_code: "+229",
        code: "BJ",
        flag: BjFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Bermuda",
        dial_code: "+1441",
        code: "BM",
        flag: BmFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Bhutan",
        dial_code: "+975",
        code: "BT",
        flag: BtFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Bolivia",
        dial_code: "+591",
        code: "BO",
        flag: BoFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Bosnia and Herzegovina",
        dial_code: "+387",
        code: "BA",
        flag: BaFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Botswana",
        dial_code: "+267",
        code: "BW",
        flag: BwFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Brazil",
        dial_code: "+55",
        code: "BR",
        flag: BrFlag as React.ComponentType<SVGRProps>,
    },

    {
        name: "Brunei Darussalam",
        dial_code: "+673",
        code: "BN",
        flag: BnFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Bulgaria",
        dial_code: "+359",
        code: "BG",
        flag: BgFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Burkina Faso",
        dial_code: "+226",
        code: "BF",
        flag: BfFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Burundi",
        dial_code: "+257",
        code: "BI",
        flag: BiFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Cambodia",
        dial_code: "+855",
        code: "KH",
        flag: KhFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Cameroon",
        dial_code: "+237",
        code: "CM",
        flag: Cfmlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Canada",
        dial_code: "+1",
        code: "CA",
        flag: CaFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Catalonia",
        dial_code: "+34",
        code: "CAT",
        flag: CatFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Cape Verde",
        dial_code: "+238",
        code: "CV",
        flag: CvFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Cayman Islands",
        dial_code: "+ 345",
        code: "KY",
        flag: KyFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Central African Republic",
        dial_code: "+236",
        code: "CF",
        flag: CfFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Chad",
        dial_code: "+235",
        code: "TD",
        flag: TdFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Chile",
        dial_code: "+56",
        code: "CL",
        flag: ClFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "China",
        dial_code: "+86",
        code: "CN",
        flag: CnFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Colombia",
        dial_code: "+57",
        code: "CO",
        flag: CoFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Comoros",
        dial_code: "+269",
        code: "KM",
        flag: KmFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Congo",
        dial_code: "+242",
        code: "CG",
        flag: CgFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Congo, The Democratic Republic of the Congo",
        dial_code: "+243",
        code: "CD",
        flag: CdFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Costa Rica",
        dial_code: "+506",
        code: "CR",
        flag: CrFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Cote d'Ivoire",
        dial_code: "+225",
        code: "CI",
        flag: CiFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Croatia",
        dial_code: "+385",
        code: "HR",
        flag: HrFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Cuba",
        dial_code: "+53",
        code: "CU",
        flag: CuFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Cyprus",
        dial_code: "+357",
        code: "CY",
        flag: CyFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Czech Republic",
        dial_code: "+420",
        code: "CZ",
        flag: CzFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Denmark",
        dial_code: "+45",
        code: "DK",
        flag: DkFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Djibouti",
        dial_code: "+253",
        code: "DJ",
        flag: DjFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Dominica",
        dial_code: "+1767",
        code: "DM",
        flag: DmFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Dominican Republic",
        dial_code: "+1849",
        code: "DO",
        flag: DoFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Ecuador",
        dial_code: "+593",
        code: "EC",
        flag: ECFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Egypt",
        dial_code: "+20",
        code: "EG",
        flag: EGFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "El Salvador",
        dial_code: "+503",
        code: "SV",
        flag: SVFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Equatorial Guinea",
        dial_code: "+240",
        code: "GQ",
        flag: GQFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Eritrea",
        dial_code: "+291",
        code: "ER",
        flag: ERFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Estonia",
        dial_code: "+372",
        code: "EE",
        flag: EEFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Ethiopia",
        dial_code: "+251",
        code: "ET",
        flag: ETFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Falkland Islands (Malvinas)",
        dial_code: "+500",
        code: "FK",
        flag: FKFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Faroe Islands",
        dial_code: "+298",
        code: "FO",
        flag: FOFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Fiji",
        dial_code: "+679",
        code: "FJ",
        flag: FJFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Finland",
        dial_code: "+358",
        code: "FI",
        flag: FIFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "France",
        dial_code: "+33",
        code: "FR",
        flag: FRFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "French Guiana",
        dial_code: "+594",
        code: "GF",
        flag: GFFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "French Polynesia",
        dial_code: "+689",
        code: "PF",
        flag: PFFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Gabon",
        dial_code: "+241",
        code: "GA",
        flag: GAFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Gambia",
        dial_code: "+220",
        code: "GM",
        flag: GMFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Georgia",
        dial_code: "+995",
        code: "GE",
        flag: GEFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Germany",
        dial_code: "+49",
        code: "DE",
        flag: DEFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Ghana",
        dial_code: "+233",
        code: "GH",
        flag: GHFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Gibraltar",
        dial_code: "+350",
        code: "GI",
        flag: GIFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Greece",
        dial_code: "+30",
        code: "GR",
        flag: GRFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Greenland",
        dial_code: "+299",
        code: "GL",
        flag: GLFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Grenada",
        dial_code: "+1473",
        code: "GD",
        flag: GDFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Guadeloupe",
        dial_code: "+590",
        code: "GP",
        flag: GPFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Guam",
        dial_code: "+1671",
        code: "GU",
        flag: GUFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Guatemala",
        dial_code: "+502",
        code: "GT",
        flag: GTFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Guernsey",
        dial_code: "+44",
        code: "GG",
        flag: GGFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Guinea",
        dial_code: "+224",
        code: "GN",
        flag: GNFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Guinea-Bissau",
        dial_code: "+245",
        code: "GW",
        flag: GWFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Guyana",
        dial_code: "+595",
        code: "GY",
        flag: GYFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Haiti",
        dial_code: "+509",
        code: "HT",
        flag: HTFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Holy See (Vatican City State)",
        dial_code: "+379",
        code: "VA",
        flag: VAFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Honduras",
        dial_code: "+504",
        code: "HN",
        flag: HNFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Hong Kong",
        dial_code: "+852",
        code: "HK",
        flag: HKFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Hungary",
        dial_code: "+36",
        code: "HU",
        flag: HUFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Iceland",
        dial_code: "+354",
        code: "IS",
        flag: ISFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "India",
        dial_code: "+91",
        code: "IN",
        flag: INFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Indonesia",
        dial_code: "+62",
        code: "ID",
        flag: IDFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Iran, Islamic Republic of Persian Gulf",
        dial_code: "+98",
        code: "IR",
        flag: IRFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Iraq",
        dial_code: "+964",
        code: "IQ",
        flag: IQFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Ireland",
        dial_code: "+353",
        code: "IE",
        flag: IEFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Isle of Man",
        dial_code: "+44",
        code: "IM",
        flag: IMFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Israel",
        dial_code: "+972",
        code: "IL",
        flag: ILFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Italy",
        dial_code: "+39",
        code: "IT",
        flag: ITFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Jamaica",
        dial_code: "+1876",
        code: "JM",
        flag: JMFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Japan",
        dial_code: "+81",
        code: "JP",
        flag: JPFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Jersey",
        dial_code: "+44",
        code: "JE",
        flag: JEFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Jordan",
        dial_code: "+962",
        code: "JO",
        flag: JOFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Kazakhstan",
        dial_code: "+77",
        code: "KZ",
        flag: KZFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Kenya",
        dial_code: "+254",
        code: "KE",
        flag: KEFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Kiribati",
        dial_code: "+686",
        code: "KI",
        flag: KIFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Korea, Democratic People's Republic of Korea",
        dial_code: "+850",
        code: "KP",
        flag: KPFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Korea, Republic of South Korea",
        dial_code: "+82",
        code: "KR",
        flag: KRFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Kuwait",
        dial_code: "+965",
        code: "KW",
        flag: KWFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Kyrgyzstan",
        dial_code: "+996",
        code: "KG",
        flag: KGFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Laos",
        dial_code: "+856",
        code: "LA",
        flag: LAFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Latvia",
        dial_code: "+371",
        code: "LV",
        flag: LVFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Lebanon",
        dial_code: "+961",
        code: "LB",
        flag: LBFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Lesotho",
        dial_code: "+266",
        code: "LS",
        flag: LSFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Liberia",
        dial_code: "+231",
        code: "LR",
        flag: LRFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Libyan Arab Jamahiriya",
        dial_code: "+218",
        code: "LY",
        flag: LYFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Liechtenstein",
        dial_code: "+423",
        code: "LI",
        flag: LIFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Lithuania",
        dial_code: "+370",
        code: "LT",
        flag: LTFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Luxembourg",
        dial_code: "+352",
        code: "LU",
        flag: LUFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Macao",
        dial_code: "+853",
        code: "MO",
        flag: MOFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Macedonia",
        dial_code: "+389",
        code: "MK",
        flag: MKFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Madagascar",
        dial_code: "+261",
        code: "MG",
        flag: MGFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Malawi",
        dial_code: "+265",
        code: "MW",
        flag: MWFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Malaysia",
        dial_code: "+60",
        code: "MY",
        flag: MYFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Maldives",
        dial_code: "+960",
        code: "MV",
        flag: MVFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Mali",
        dial_code: "+223",
        code: "ML",
        flag: MLFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Malta",
        dial_code: "+356",
        code: "MT",
        flag: MTFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Marshall Islands",
        dial_code: "+692",
        code: "MH",
        flag: MHFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Martinique",
        dial_code: "+596",
        code: "MQ",
        flag: MQFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Mauritania",
        dial_code: "+222",
        code: "MR",
        flag: MRFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Mauritius",
        dial_code: "+230",
        code: "MU",
        flag: MUFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Mayotte",
        dial_code: "+262",
        code: "YT",
        flag: YTFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Mexico",
        dial_code: "+52",
        code: "MX",
        flag: MXFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Micronesia, Federated States of Micronesia",
        dial_code: "+691",
        code: "FM",
        flag: FMFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Moldova",
        dial_code: "+373",
        code: "MD",
        flag: MDFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Monaco",
        dial_code: "+377",
        code: "MC",
        flag: MCFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Mongolia",
        dial_code: "+976",
        code: "MN",
        flag: MNFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Montenegro",
        dial_code: "+382",
        code: "ME",
        flag: MEFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Montserrat",
        dial_code: "+1664",
        code: "MS",
        flag: MSFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Morocco",
        dial_code: "+212",
        code: "MA",
        flag: MAFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Mozambique",
        dial_code: "+258",
        code: "MZ",
        flag: MZFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Myanmar",
        dial_code: "+95",
        code: "MM",
        flag: MMFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Namibia",
        dial_code: "+264",
        code: "NA",
        flag: NAFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Nauru",
        dial_code: "+674",
        code: "NR",
        flag: NRFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Nepal",
        dial_code: "+977",
        code: "NP",
        flag: NPFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Netherlands",
        dial_code: "+31",
        code: "NL",
        flag: NLFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Caribbean Netherlands",
        dial_code: "+599",
        code: "BQ",
        flag: BQFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "New Caledonia",
        dial_code: "+687",
        code: "NC",
        flag: NCFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "New Zealand",
        dial_code: "+64",
        code: "NZ",
        flag: NZFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Nicaragua",
        dial_code: "+505",
        code: "NI",
        flag: NIFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Niger",
        dial_code: "+227",
        code: "NE",
        flag: NEFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Nigeria",
        dial_code: "+234",
        code: "NG",
        flag: NGFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Niue",
        dial_code: "+683",
        code: "NU",
        flag: NUFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Norfolk Island",
        dial_code: "+672",
        code: "NF",
        flag: NFFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Northern Mariana Islands",
        dial_code: "+1670",
        code: "MP",
        flag: MPFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Norway",
        dial_code: "+47",
        code: "NO",
        flag: NOFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Oman",
        dial_code: "+968",
        code: "OM",
        flag: OMFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Pakistan",
        dial_code: "+92",
        code: "PK",
        flag: PKFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Palau",
        dial_code: "+680",
        code: "PW",
        flag: PWFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Palestinian Territory, Occupied",
        dial_code: "+970",
        code: "PS",
        flag: PSFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Panama",
        dial_code: "+507",
        code: "PA",
        flag: PAFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Papua New Guinea",
        dial_code: "+675",
        code: "PG",
        flag: PGFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Paraguay",
        dial_code: "+595",
        code: "PY",
        flag: PYFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Peru",
        dial_code: "+51",
        code: "PE",
        flag: PEFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Philippines",
        dial_code: "+63",
        code: "PH",
        flag: PHFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Pitcairn",
        dial_code: "+872",
        code: "PN",
        flag: PNFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Poland",
        dial_code: "+48",
        code: "PL",
        flag: PLFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Portugal",
        dial_code: "+351",
        code: "PT",
        flag: PTFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Puerto Rico",
        dial_code: "+1939",
        code: "PR",
        flag: PRFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Qatar",
        dial_code: "+974",
        code: "QA",
        flag: QAFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Romania",
        dial_code: "+40",
        code: "RO",
        flag: ROFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Russia",
        dial_code: "+7",
        code: "RU",
        flag: RUFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Rwanda",
        dial_code: "+250",
        code: "RW",
        flag: RWFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Reunion",
        dial_code: "+262",
        code: "RE",
        flag: REFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Saint Barthelemy",
        dial_code: "+590",
        code: "BL",
        flag: BLFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Saint Helena, Ascension and Tristan Da Cunha",
        dial_code: "+290",
        code: "SH",
        flag: SHFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Saint Kitts and Nevis",
        dial_code: "+1869",
        code: "KN",
        flag: KNFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Saint Lucia",
        dial_code: "+1758",
        code: "LC",
        flag: LCFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Saint Martin",
        dial_code: "+590",
        code: "MF",
        flag: MFFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Saint Pierre and Miquelon",
        dial_code: "+508",
        code: "PM",
        flag: PMFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Saint Vincent and the Grenadines",
        dial_code: "+1784",
        code: "VC",
        flag: VCFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Samoa",
        dial_code: "+685",
        code: "WS",
        flag: WSFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "San Marino",
        dial_code: "+378",
        code: "SM",
        flag: SMFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Sao Tome and Principe",
        dial_code: "+239",
        code: "ST",
        flag: STFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Saudi Arabia",
        dial_code: "+966",
        code: "SA",
        flag: SAFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Senegal",
        dial_code: "+221",
        code: "SN",
        flag: SNFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Serbia",
        dial_code: "+381",
        code: "RS",
        flag: RSFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Seychelles",
        dial_code: "+248",
        code: "SC",
        flag: SCFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Sierra Leone",
        dial_code: "+232",
        code: "SL",
        flag: SLFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Singapore",
        dial_code: "+65",
        code: "SG",
        flag: SGFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Slovakia",
        dial_code: "+421",
        code: "SK",
        flag: SKFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Slovenia",
        dial_code: "+386",
        code: "SI",
        flag: SIFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Solomon Islands",
        dial_code: "+677",
        code: "SB",
        flag: SBFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Somalia",
        dial_code: "+252",
        code: "SO",
        flag: SOFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "South Africa",
        dial_code: "+27",
        code: "ZA",
        flag: ZAFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "South Sudan",
        dial_code: "+211",
        code: "SS",
        flag: SSFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "South Georgia and the South Sandwich Islands",
        dial_code: "+500",
        code: "GS",
        flag: GSFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Spain",
        dial_code: "+34",
        code: "ES",
        flag: ESFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Sri Lanka",
        dial_code: "+94",
        code: "LK",
        flag: LKFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Sudan",
        dial_code: "+249",
        code: "SD",
        flag: SDFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Suriname",
        dial_code: "+597",
        code: "SR",
        flag: SRFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Svalbard and Jan Mayen",
        dial_code: "+47",
        code: "SJ",
        flag: SJFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Swaziland",
        dial_code: "+268",
        code: "SZ",
        flag: SZFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Sweden",
        dial_code: "+46",
        code: "SE",
        flag: SEFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Switzerland",
        dial_code: "+41",
        code: "CH",
        flag: CHFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Syrian Arab Republic",
        dial_code: "+963",
        code: "SY",
        flag: SYFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Taiwan",
        dial_code: "+886",
        code: "TW",
        flag: TWFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Tajikistan",
        dial_code: "+992",
        code: "TJ",
        flag: TJFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Tanzania, United Republic of Tanzania",
        dial_code: "+255",
        code: "TZ",
        flag: TZFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Thailand",
        dial_code: "+66",
        code: "TH",
        flag: THFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Timor-Leste",
        dial_code: "+670",
        code: "TL",
        flag: TLFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Togo",
        dial_code: "+228",
        code: "TG",
        flag: TGFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Tokelau",
        dial_code: "+690",
        code: "TK",
        flag: TKFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Tonga",
        dial_code: "+676",
        code: "TO",
        flag: TOFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Trinidad and Tobago",
        dial_code: "+1868",
        code: "TT",
        flag: TTFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Tunisia",
        dial_code: "+216",
        code: "TN",
        flag: TNFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Turkey",
        dial_code: "+90",
        code: "TR",
        flag: TRFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Turkmenistan",
        dial_code: "+993",
        code: "TM",
        flag: TMFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Turks and Caicos Islands",
        dial_code: "+1649",
        code: "TC",
        flag: TCFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Tuvalu",
        dial_code: "+688",
        code: "TV",
        flag: TVFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Uganda",
        dial_code: "+256",
        code: "UG",
        flag: UGFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Ukraine",
        dial_code: "+380",
        code: "UA",
        flag: UAFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "United Arab Emirates",
        dial_code: "+971",
        code: "AE",
        flag: AEFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "United Kingdom",
        dial_code: "+44",
        code: "GB",
        flag: GBFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "United States",
        dial_code: "+1",
        code: "US",
        flag: USFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Uruguay",
        dial_code: "+598",
        code: "UY",
        flag: UYFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Uzbekistan",
        dial_code: "+998",
        code: "UZ",
        flag: UZFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Vanuatu",
        dial_code: "+678",
        code: "VU",
        flag: VUFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Venezuela, Bolivarian Republic of Venezuela",
        dial_code: "+58",
        code: "VE",
        flag: VEFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Vietnam",
        dial_code: "+84",
        code: "VN",
        flag: VNFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Virgin Islands, British",
        dial_code: "+1284",
        code: "VG",
        flag: VGFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Virgin Islands, U.S.",
        dial_code: "+1340",
        code: "VI",
        flag: VIFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Wallis and Futuna",
        dial_code: "+681",
        code: "WF",
        flag: WFFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Yemen",
        dial_code: "+967",
        code: "YE",
        flag: YEFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Zambia",
        dial_code: "+260",
        code: "ZM",
        flag: ZMFlag as React.ComponentType<SVGRProps>,
    },
    {
        name: "Zimbabwe",
        dial_code: "+263",
        code: "ZW",
        flag: ZWFlag as React.ComponentType<SVGRProps>,
    },
] as const;

export type Country = typeof countries;

export type CountryCode = Country[number]["code"];
export type CountryName = Country[number]["name"];
export type CountryDialCode = Country[number]["dial_code"];
