import { FlagCode } from "./flags";
import { FlagType } from "./types";

export type FlagData = {
    code: FlagCode;
    name: string;
    type: FlagType;
};

export const flags: FlagData[] = [
    {
        name: "Afghanistan",
        type: "country",
        code: "Af",
        // flag: Af as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Aland Islands",
        type: "country",
        code: "Ax",
        // flag: Ax as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Netherlands Antilles",
        type: "country",
        code: "An",
    },
    {
        name: "Albania",
        type: "country",
        code: "Al",
        // flag: Al as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Algeria",
        type: "country",
        code: "Dz",
        // flag: Dz as FC<ComponentProps<"svg"> & SVGRProps>,
    },

    {
        name: "Andorra",
        type: "country",
        code: "Ad",
        // flag: Ad as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Angola",
        type: "country",
        code: "Ao",
        // flag: Ao as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Anguilla",
        type: "country",
        code: "Ai",
        // flag: Ai as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Antarctica",
        type: "country",
        code: "Aq",
        // flag: Aq as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Antigua and Barbuda",
        type: "country",
        code: "Ag",
        // flag: Ag as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Argentina",
        type: "country",
        code: "Ar",
        // flag: Ar as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Armenia",
        type: "country",
        code: "Am",
        // flag: Am as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Aruba",
        type: "country",
        code: "Aw",
        // flag: Aw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Australia",
        type: "country",
        code: "Au",
        // flag: Au as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Austria",
        type: "country",
        code: "At",
        // flag: At as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Azerbaijan",
        type: "country",
        code: "Az",
        // flag: Az as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bahamas",
        type: "country",
        code: "Bs",
        // flag: Bs as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bahrain",
        type: "country",
        code: "Bh",
        // flag: Bh as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bangladesh",
        type: "country",
        code: "Bd",
        // flag: Bd as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Barbados",
        type: "country",
        code: "Bb",
        // flag: Bb as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Belarus",
        type: "country",
        code: "By",
        // flag: By as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Belgium",
        type: "country",
        code: "Be",
        // flag: Be as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Belize",
        type: "country",
        code: "Bz",
        // flag: Bz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Benin",
        type: "country",
        code: "Bj",
        // flag: Bj as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bermuda",
        type: "country",
        code: "Bm",
        // flag: Bm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bhutan",
        type: "country",
        code: "Bt",
        // flag: Bt as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bolivia",
        type: "country",
        code: "Bo",
        // flag: Bo as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bosnia and Herzegovina",
        type: "country",
        code: "Ba",
        // flag: Ba as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Botswana",
        type: "country",
        code: "Bw",
        // flag: Bw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Brazil",
        type: "country",
        code: "Br",
        // flag: Br as FC<ComponentProps<"svg"> & SVGRProps>,
    },

    {
        name: "Brunei Darussalam",
        type: "country",
        code: "Bn",
        // flag: Bn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bulgaria",
        type: "country",
        code: "Bg",
        // flag: Bg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Burkina Faso",
        type: "country",
        code: "Bf",
        // flag: Bf as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Burundi",
        type: "country",
        code: "Bi",
        // flag: Bi as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cambodia",
        type: "country",
        code: "Kh",
        // flag: Kh as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cameroon",
        type: "country",
        code: "Cm",
        // flag: Cm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Canada",
        type: "country",
        code: "Ca",
        // flag: Ca as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cape Verde",
        type: "country",
        code: "Cv",
        // flag: Cv as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cayman Islands",
        type: "country",
        code: "Ky",
        // flag: Ky as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Central African Republic",
        type: "country",
        code: "Cf",
        // flag: Cf as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Chad",
        type: "country",
        code: "Td",
        // flag: Td as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Chile",
        type: "country",
        code: "Cl",
        // flag: Cl as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "China",
        type: "country",
        code: "Cn",
        // flag: Cn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Colombia",
        type: "country",
        code: "Co",
        // flag: Co as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Comoros",
        type: "country",
        code: "Km",
        // flag: Km as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Congo",
        type: "country",
        code: "Cg",
        // flag: Cg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Congo (RDC)",
        type: "country",
        code: "Cd",
        // flag: Cd as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Costa Rica",
        type: "country",
        code: "Cr",
        // flag: Cr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cote d'Ivoire",
        type: "country",
        code: "Ci",
        // flag: Ci as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Croatia",
        type: "country",
        code: "Hr",
        // flag: Hr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cuba",
        type: "country",
        code: "Cu",
        // flag: Cu as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cyprus",
        type: "country",
        code: "Cy",
        // flag: Cy as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Czech Republic",
        type: "country",
        code: "Cz",
        // flag: Cz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Denmark",
        type: "country",
        code: "Dk",
        // flag: Dk as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Djibouti",
        type: "country",
        code: "Dj",
        // flag: Dj as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Dominica",
        type: "country",
        code: "Dm",
        // flag: Dm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Dominican Republic",
        type: "country",
        code: "Do",
        // flag: Do as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Ecuador",
        type: "country",
        code: "Ec",
        // flag: Ec as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Egypt",
        type: "country",
        code: "Eg",
        // flag: Eg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "El Salvador",
        type: "country",
        code: "Sv",
        // flag: Sv as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Equatorial Guinea",
        type: "country",
        code: "Gq",
        // flag: Gq as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Eritrea",
        type: "country",
        code: "Er",
        // flag: Er as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Estonia",
        type: "country",
        code: "Ee",
        // flag: Ee as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Ethiopia",
        type: "country",
        code: "Et",
        // flag: Et as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Falkland Islands (Malvinas)",
        type: "country",
        code: "Fk",
        // flag: Fk as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Fiji",
        type: "country",
        code: "Fj",
        // flag: Fj as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Finland",
        type: "country",
        code: "Fi",
        // flag: Fi as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "France",
        type: "country",
        code: "Fr",
        // flag: Fr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "French Polynesia",
        type: "country",
        code: "Pf",
        // flag: Pf as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Gabon",
        type: "country",
        code: "Ga",
        // flag: Ga as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Gambia",
        type: "country",
        code: "Gm",
        // flag: Gm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Georgia",
        type: "country",
        code: "Ge",
        // flag: Ge as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Germany",
        type: "country",
        code: "De",
        // flag: De as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Ghana",
        type: "country",
        code: "Gh",
        // flag: Gh as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Gibraltar",
        type: "country",
        code: "Gi",
        // flag: Gi as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Greece",
        type: "country",
        code: "Gr",
        // flag: Gr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Greenland",
        type: "country",
        code: "Gl",
        // flag: Gl as FC<ComponentProps<"svg"> & SVGRProps>,
    },

    {
        name: "Guatemala",
        type: "country",
        code: "Gt",
        // flag: Gt as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Guernsey",
        type: "country",
        code: "Gg",
        // flag: Gg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Guinea",
        type: "country",
        code: "Gn",
        // flag: Gn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Guinea-Bissau",
        type: "country",
        code: "Gw",
        // flag: Gw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Guyana",
        type: "country",
        code: "Gy",
        // flag: Gy as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Haiti",
        type: "country",
        code: "Ht",
        // flag: Ht as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Vatican City",
        type: "country",
        code: "Va",
        // flag: Va as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Honduras",
        type: "country",
        code: "Hn",
        // flag: Hn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Hong Kong",
        type: "country",
        code: "Hk",
        // flag: Hk as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Hungary",
        type: "country",
        code: "Hu",
        // flag: Hu as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Iceland",
        type: "country",
        code: "Is",
        // flag: Is as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "India",
        type: "country",
        code: "In",
        // flag: In as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Indonesia",
        type: "country",
        code: "Id",
        // flag: Id as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Iran",
        type: "country",
        code: "Ir",
        // flag: Ir as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Iraq",
        type: "country",
        code: "Iq",
        // flag: Iq as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Ireland",
        type: "country",
        code: "Ie",
        // flag: Ie as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Isle of Man",
        type: "country",
        code: "Im",
        // flag: Im as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Israel",
        type: "country",
        code: "Il",
        // flag: Il as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Italy",
        type: "country",
        code: "It",
        // flag: It as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Jamaica",
        type: "country",
        code: "Jm",
        // flag: Jm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Japan",
        type: "country",
        code: "Jp",
        // flag: Jp as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Jersey",
        type: "country",
        code: "Je",
        // flag: Je as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Jordan",
        type: "country",
        code: "Jo",
        // flag: Jo as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Kazakhstan",
        type: "country",
        code: "Kz",
        // flag: Kz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Kenya",
        type: "country",
        code: "Ke",
        // flag: Ke as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "North Korea",
        type: "country",
        code: "Kp",
        // flag: Kp as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "South Korea",
        type: "country",
        code: "Kr",
        // flag: Kr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Kuwait",
        type: "country",
        code: "Kw",
        // flag: Kw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Kyrgyzstan",
        type: "country",
        code: "Kg",
        // flag: Kg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Laos",
        type: "country",
        code: "La",
        // flag: La as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Latvia",
        type: "country",
        code: "Lv",
        // flag: Lv as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Lebanon",
        type: "country",
        code: "Lb",
        // flag: Lb as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Lesotho",
        type: "country",
        code: "Ls",
        // flag: Ls as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Liberia",
        type: "country",
        code: "Lr",
        // flag: Lr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Libyan Arab Jamahiriya",
        type: "country",
        code: "Ly",
        // flag: Ly as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Liechtenstein",
        type: "country",
        code: "Li",
        // flag: Li as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Lithuania",
        type: "country",
        code: "Lt",
        // flag: Li as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Luxembourg",
        type: "country",
        code: "Lu",
        // flag: Lu as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Macao",
        type: "country",
        code: "Mo",
        // flag: Mo as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Macedonia",
        type: "country",
        code: "Mk",
        // flag: Mk as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Madagascar",
        type: "country",
        code: "Mg",
        // flag: Mg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Malawi",
        type: "country",
        code: "Mw",
        // flag: Mw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Malaysia",
        type: "country",
        code: "My",
        // flag: My as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Maldives",
        type: "country",
        code: "Mv",
        // flag: Mv as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Mali",
        type: "country",
        code: "Ml",
        // flag: Ml as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Malta",
        type: "country",
        code: "Mt",
        // flag: Mt as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Mauritania",
        type: "country",
        code: "Mr",
        // flag: Mr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Mauritius",
        type: "country",
        code: "Mu",
        // flag: Mu as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Mexico",
        type: "country",
        code: "Mx",
        // flag: Mx as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Micronesia",
        type: "country",
        code: "Fm",
        // flag: Fm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Moldova",
        type: "country",
        code: "Md",
        // flag: Md as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Monaco",
        type: "country",
        code: "Mc",
        // flag: Mc as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Mongolia",
        type: "country",
        code: "Mn",
        // flag: Mn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Montenegro",
        type: "country",
        code: "Me",
        // flag: Me as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Montserrat",
        type: "country",
        code: "Ms",
        // flag: Ms as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Morocco",
        type: "country",
        code: "Ma",
        // flag: Ma as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Mozambique",
        type: "country",
        code: "Mz",
        // flag: Mz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Myanmar",
        type: "country",
        code: "Mm",
        // flag: Mm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Namibia",
        type: "country",
        code: "Na",
        // flag: Na as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Nepal",
        type: "country",
        code: "Np",
        // flag: Np as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Netherlands",
        type: "country",
        code: "Nl",
        // flag: Nl as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "New Zealand",
        type: "country",
        code: "Nz",
        // flag: Nz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Nicaragua",
        type: "country",
        code: "Ni",
        // flag: Ni as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Niger",
        type: "country",
        code: "Ne",
        // flag: Ne as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Nigeria",
        type: "country",
        code: "Ng",
        // flag: Ng as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Norway",
        type: "country",
        code: "No",
        // flag: No as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Oman",
        type: "country",
        code: "Om",
        // flag: Om as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Pakistan",
        type: "country",
        code: "Pk",
        // flag: Pk as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Palau",
        type: "country",
        code: "Pw",
        // flag: Pw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Panama",
        type: "country",
        code: "Pa",
        // flag: Pa as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Papua New Guinea",
        type: "country",
        code: "Pg",
        // flag: Pg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Paraguay",
        type: "country",
        code: "Py",
        // flag: Py as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Peru",
        type: "country",
        code: "Pe",
        // flag: Pe as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Philippines",
        type: "country",
        code: "Ph",
        // flag: Ph as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Poland",
        type: "country",
        code: "Pl",
        // flag: Pl as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Portugal",
        type: "country",
        code: "Pt",
        // flag: Pt as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Puerto Rico",
        type: "country",
        code: "Pr",
        // flag: Pr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Qatar",
        type: "country",
        code: "Qa",
        // flag: Qa as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Romania",
        type: "country",
        code: "Ro",
        // flag: Ro as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Russia",
        type: "country",
        code: "Ru",
        // flag: Ru as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Rwanda",
        type: "country",
        code: "Rw",
        // flag: Rw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Saint Helena",
        type: "country",
        code: "Sh",
        // flag: Sh as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Saint Kitts and Nevis",
        type: "country",
        code: "Kn",
        // flag: Kn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Saint Lucia",
        type: "country",
        code: "Lc",
        // flag: Lc as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Saint Vincent and the Grenadines",
        type: "country",
        code: "Vc",
        // flag: Vc as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Samoa",
        type: "country",
        code: "Ws",
        // flag: Ws as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "San Marino",
        type: "country",
        code: "Sm",
        // flag: Sm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Sao Tome and Principe",
        type: "country",
        code: "St",
        // flag: St as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Saudi Arabia",
        type: "country",
        code: "Sa",
        // flag: Sa as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Senegal",
        type: "country",
        code: "Sn",
        // flag: Sn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Serbia",
        type: "country",
        code: "Rs",
        // flag: Rs as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Seychelles",
        type: "country",
        code: "Sc",
        // flag: Sc as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Sierra Leone",
        type: "country",
        code: "Sl",
        // flag: Sl as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Singapore",
        type: "country",
        code: "Sg",
        // flag: Sg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Slovakia",
        type: "country",
        code: "Sk",
        // flag: Sk as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Slovenia",
        type: "country",
        code: "Si",
        // flag: Si as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Solomon Islands",
        type: "country",
        code: "Sb",
        // flag: Sb as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Somalia",
        type: "country",
        code: "So",
        // flag: So as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "South Africa",
        type: "country",
        code: "Za",
        // flag: Za as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Spain",
        type: "country",
        code: "Es",
        // flag: Es as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Sri Lanka",
        type: "country",
        code: "Lk",
        // flag: Lk as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Sudan",
        type: "country",
        code: "Sd",
        // flag: Sd as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Suriname",
        type: "country",
        code: "Sr",
        // flag: Sr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Swaziland",
        type: "country",
        code: "Sz",
        // flag: Sz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Sweden",
        type: "country",
        code: "Se",
        // flag: Se as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Switzerland",
        type: "country",
        code: "Ch",
        // flag: Ch as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Syrian Arab Republic",
        type: "country",
        code: "Sy",
        // flag: Sy as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Taiwan",
        type: "country",
        code: "Tw",
        // flag: Tw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Tajikistan",
        type: "country",
        code: "Tj",
        // flag: Tj as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Tanzania",
        type: "country",
        code: "Tz",
        // flag: Tz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Thailand",
        type: "country",
        code: "Th",
        // flag: Th as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Timor-Leste",
        type: "country",
        code: "Tl",
        // flag: Tl as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Togo",
        type: "country",
        code: "Tg",
        // flag: Tg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Tonga",
        type: "country",
        code: "To",
        // flag: To as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Trinidad and Tobago",
        type: "country",
        code: "Tt",
        // flag: Tt as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Tunisia",
        type: "country",
        code: "Tn",
        // flag: Tn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Turkey",
        type: "country",
        code: "Tr",
        // flag: Tr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Turkmenistan",
        type: "country",
        code: "Tm",
        // flag: Tm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Turks and Caicos Islands",
        type: "country",
        code: "Tc",
        // flag: Tc as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Uganda",
        type: "country",
        code: "Ug",
        // flag: Ug as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Ukraine",
        type: "country",
        code: "Ua",
        // flag: Ua as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "United Arab Emirates",
        type: "country",
        code: "Ae",
        // flag: Ae as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "United Kingdom",
        type: "country",
        code: "Gb",
        // flag: Gb as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Grenada",
        type: "country",
        code: "Gd",
    },
    {
        name: "United States",
        type: "country",
        code: "Us",
        // flag: Us as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Uruguay",
        type: "country",
        code: "Uy",
        // flag: Uy as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Uzbekistan",
        type: "country",
        code: "Uz",
        // flag: Uz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Vanuatu",
        type: "country",
        code: "Vu",
        // flag: Vu as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Venezuela",
        type: "country",
        code: "Ve",
        // flag: Ve as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Vietnam",
        type: "country",
        code: "Vn",
        // flag: Vn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Virgin Islands",
        type: "country",
        code: "Vg",
        // flag: Vg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Yemen",
        type: "country",
        code: "Ye",
        // flag: Ye as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Zambia",
        type: "country",
        code: "Zm",
        // flag: Zm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Zimbabwe",
        type: "country",
        code: "Zw",
        // flag: Zw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "World",
        type: "world",
        code: "Ww",
        // flag: Ww as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "North America",
        type: "world",
        code: "Cna",
        // flag: Cna as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "South America",
        type: "world",
        code: "Csa",
        // flag: Csa as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Africa",
        type: "world",
        code: "Caf",
        // flag: Caf as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Europe",
        type: "world",
        code: "Ceu",
        // flag: Ceu as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Asia",
        type: "world",
        code: "Cas",
        // flag: Cas as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Oceania",
        type: "world",
        code: "Coc",
        // flag: Coc as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "European Union",
        type: "region",
        code: "Eu",
        // flag: Eu as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Catalonia",
        type: "region",
        code: "EsCataluna",
        // flag: EsCataluna as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Aragon",
        type: "region",
        code: "EsAragon",
        // flag: EsAragon as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Valencia",
        type: "region",
        code: "EsValencia",
        // flag: EsValencia as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Balearic Islands",
        type: "region",
        code: "EsBalear",
        // flag: EsBalear as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Andalusia",
        type: "region",
        code: "EsAndalucia",
        // flag: EsAndalucia as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Extremadura",
        type: "region",
        code: "EsExtremadura",
        // flag: EsExtremadura as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Galicia",
        type: "region",
        code: "EsGalicia",
        // flag: EsGalicia as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Navarra",
        type: "region",
        code: "EsNavarra",
        // flag: EsNavarra as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Canary Islands",
        type: "region",
        code: "EsCanarias",
        // flag: EsCanarias as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Madrid",
        type: "region",
        code: "EsMadrid",
        // flag: EsMadrid as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Asturias",
        type: "region",
        code: "EsAsturias",
        // flag: EsAsturias as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Basque Country",
        type: "region",
        code: "EsBasco",
        // flag: EsBasco as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Rioja",
        type: "region",
        code: "EsRioja",
        // flag: EsRioja as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cantabria",
        type: "region",
        code: "EsCantabria",
        // flag: EsCantabria as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Castile and León",
        type: "region",
        code: "EsLeon",
        // flag: EsLeon as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Castile-La Mancha",
        type: "region",
        code: "EsMancha",
        // flag: EsMancha as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Murcia",
        type: "region",
        code: "EsMurcia",
        // flag: EsMurcia as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Almería",
        type: "city",
        code: "EsAlmeria",
        // flag: EsAlmeria as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Barcelona",
        type: "city",
        code: "EsBarcelona",
        // flag: EsBarcelona as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Girona",
        type: "city",
        code: "EsGirona",
        // flag: EsGirona as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Tarragona",
        type: "city",
        code: "EsTarragona",
        // flag: EsTarragona as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Premià (Mar)",
        type: "city",
        code: "EsPremiaMar",
    },
    {
        name: "Ourense",
        type: "city",
        code: "EsOurense",
        // flag: EsOurense as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Mataró",
        type: "city",
        code: "EsMataro",
        // flag: EsMataro as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cruz de Borgoña",
        type: "historical",
        code: "EsBorgona",
        // flag: EsBorgona as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Republic of Spain",
        type: "historical",
        code: "EsRepublica",
        // flag: EsRepublica as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "LGTB",
        type: "symbol",
        code: "Lgtb",
        // flag: Lgtb as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Peace",
        type: "symbol",
        code: "Peace",
    },
];
