import { FlagType } from "./types";

export const flags = [
    {
        name: "Afghanistan",
        type: "country",
        code: "AF",
        // flag: Af as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Aland Islands",
        type: "country",
        code: "AX",
        // flag: Ax as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Albania",
        type: "country",
        code: "AL",
        // flag: Al as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Algeria",
        type: "country",
        code: "DZ",
        // flag: Dz as FC<ComponentProps<"svg"> & SVGRProps>,
    },

    {
        name: "Andorra",
        type: "country",
        code: "AD",
        // flag: Ad as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Angola",
        type: "country",
        code: "AO",
        // flag: Ao as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Anguilla",
        type: "country",
        code: "AI",
        // flag: Ai as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Antarctica",
        type: "country",
        code: "AQ",
        // flag: Aq as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Antigua and Barbuda",
        type: "country",
        code: "AG",
        // flag: Ag as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Argentina",
        type: "country",
        code: "AR",
        // flag: Ar as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Armenia",
        type: "country",
        code: "AM",
        // flag: Am as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Aruba",
        type: "country",
        code: "AW",
        // flag: Aw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Australia",
        type: "country",
        code: "AU",
        // flag: Au as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Austria",
        type: "country",
        code: "AT",
        // flag: At as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Azerbaijan",
        type: "country",
        code: "AZ",
        // flag: Az as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bahamas",
        type: "country",
        code: "BS",
        // flag: Bs as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bahrain",
        type: "country",
        code: "BH",
        // flag: Bh as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bangladesh",
        type: "country",
        code: "BD",
        // flag: Bd as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Barbados",
        type: "country",
        code: "BB",
        // flag: Bb as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Belarus",
        type: "country",
        code: "BY",
        // flag: By as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Belgium",
        type: "country",
        code: "BE",
        // flag: Be as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Belize",
        type: "country",
        code: "BZ",
        // flag: Bz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Benin",
        type: "country",
        code: "BJ",
        // flag: Bj as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bermuda",
        type: "country",
        code: "BM",
        // flag: Bm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bhutan",
        type: "country",
        code: "BT",
        // flag: Bt as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bolivia",
        type: "country",
        code: "BO",
        // flag: Bo as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bosnia and Herzegovina",
        type: "country",
        code: "BA",
        // flag: Ba as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Botswana",
        type: "country",
        code: "BW",
        // flag: Bw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Brazil",
        type: "country",
        code: "BR",
        // flag: Br as FC<ComponentProps<"svg"> & SVGRProps>,
    },

    {
        name: "Brunei Darussalam",
        type: "country",
        code: "BN",
        // flag: Bn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Bulgaria",
        type: "country",
        code: "BG",
        // flag: Bg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Burkina Faso",
        type: "country",
        code: "BF",
        // flag: Bf as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Burundi",
        type: "country",
        code: "BI",
        // flag: Bi as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cambodia",
        type: "country",
        code: "KH",
        // flag: Kh as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cameroon",
        type: "country",
        code: "CM",
        // flag: Cm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Canada",
        type: "country",
        code: "CA",
        // flag: Ca as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cape Verde",
        type: "country",
        code: "CV",
        // flag: Cv as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cayman Islands",
        type: "country",
        code: "KY",
        // flag: Ky as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Central African Republic",
        type: "country",
        code: "CF",
        // flag: Cf as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Chad",
        type: "country",
        code: "TD",
        // flag: Td as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Chile",
        type: "country",
        code: "CL",
        // flag: Cl as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "China",
        type: "country",
        code: "CN",
        // flag: Cn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Colombia",
        type: "country",
        code: "CO",
        // flag: Co as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Comoros",
        type: "country",
        code: "KM",
        // flag: Km as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Congo",
        type: "country",
        code: "CG",
        // flag: Cg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Congo (RDC)",
        type: "country",
        code: "CD",
        // flag: Cd as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Costa Rica",
        type: "country",
        code: "CR",
        // flag: Cr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cote d'Ivoire",
        type: "country",
        code: "CI",
        // flag: Ci as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Croatia",
        type: "country",
        code: "HR",
        // flag: Hr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cuba",
        type: "country",
        code: "CU",
        // flag: Cu as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cyprus",
        type: "country",
        code: "CY",
        // flag: Cy as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Czech Republic",
        type: "country",
        code: "CZ",
        // flag: Cz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Denmark",
        type: "country",
        code: "DK",
        // flag: Dk as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Djibouti",
        type: "country",
        code: "DJ",
        // flag: Dj as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Dominica",
        type: "country",
        code: "DM",
        // flag: Dm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Dominican Republic",
        type: "country",
        code: "DO",
        // flag: Do as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Ecuador",
        type: "country",
        code: "EC",
        // flag: Ec as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Egypt",
        type: "country",
        code: "EG",
        // flag: Eg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "El Salvador",
        type: "country",
        code: "SV",
        // flag: Sv as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Equatorial Guinea",
        type: "country",
        code: "GQ",
        // flag: Gq as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Eritrea",
        type: "country",
        code: "ER",
        // flag: Er as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Estonia",
        type: "country",
        code: "EE",
        // flag: Ee as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Ethiopia",
        type: "country",
        code: "ET",
        // flag: Et as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Falkland Islands (Malvinas)",
        type: "country",
        code: "FK",
        // flag: Fk as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Fiji",
        type: "country",
        code: "FJ",
        // flag: Fj as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Finland",
        type: "country",
        code: "FI",
        // flag: Fi as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "France",
        type: "country",
        code: "FR",
        // flag: Fr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "French Polynesia",
        type: "country",
        code: "PF",
        // flag: Pf as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Gabon",
        type: "country",
        code: "GA",
        // flag: Ga as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Gambia",
        type: "country",
        code: "GM",
        // flag: Gm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Georgia",
        type: "country",
        code: "GE",
        // flag: Ge as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Germany",
        type: "country",
        code: "DE",
        // flag: De as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Ghana",
        type: "country",
        code: "GH",
        // flag: Gh as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Gibraltar",
        type: "country",
        code: "GI",
        // flag: Gi as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Greece",
        type: "country",
        code: "GR",
        // flag: Gr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Greenland",
        type: "country",
        code: "GL",
        // flag: Gl as FC<ComponentProps<"svg"> & SVGRProps>,
    },

    {
        name: "Guatemala",
        type: "country",
        code: "GT",
        // flag: Gt as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Guernsey",
        type: "country",
        code: "GG",
        // flag: Gg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Guinea",
        type: "country",
        code: "GN",
        // flag: Gn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Guinea-Bissau",
        type: "country",
        code: "GW",
        // flag: Gw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Guyana",
        type: "country",
        code: "GY",
        // flag: Gy as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Haiti",
        type: "country",
        code: "HT",
        // flag: Ht as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Vatican City",
        type: "country",
        code: "VA",
        // flag: Va as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Honduras",
        type: "country",
        code: "HN",
        // flag: Hn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Hong Kong",
        type: "country",
        code: "HK",
        // flag: Hk as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Hungary",
        type: "country",
        code: "HU",
        // flag: Hu as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Iceland",
        type: "country",
        code: "IS",
        // flag: Is as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "India",
        type: "country",
        code: "IN",
        // flag: In as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Indonesia",
        type: "country",
        code: "ID",
        // flag: Id as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Iran",
        type: "country",
        code: "IR",
        // flag: Ir as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Iraq",
        type: "country",
        code: "IQ",
        // flag: Iq as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Ireland",
        type: "country",
        code: "IE",
        // flag: Ie as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Isle of Man",
        type: "country",
        code: "IM",
        // flag: Im as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Israel",
        type: "country",
        code: "IL",
        // flag: Il as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Italy",
        type: "country",
        code: "IT",
        // flag: It as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Jamaica",
        type: "country",
        code: "JM",
        // flag: Jm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Japan",
        type: "country",
        code: "JP",
        // flag: Jp as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Jersey",
        type: "country",
        code: "JE",
        // flag: Je as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Jordan",
        type: "country",
        code: "JO",
        // flag: Jo as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Kazakhstan",
        type: "country",
        code: "KZ",
        // flag: Kz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Kenya",
        type: "country",
        code: "KE",
        // flag: Ke as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "North Korea",
        type: "country",
        code: "KP",
        // flag: Kp as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "South Korea",
        type: "country",
        code: "KR",
        // flag: Kr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Kuwait",
        type: "country",
        code: "KW",
        // flag: Kw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Kyrgyzstan",
        type: "country",
        code: "KG",
        // flag: Kg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Laos",
        type: "country",
        code: "LA",
        // flag: La as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Latvia",
        type: "country",
        code: "LV",
        // flag: Lv as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Lebanon",
        type: "country",
        code: "LB",
        // flag: Lb as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Lesotho",
        type: "country",
        code: "LS",
        // flag: Ls as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Liberia",
        type: "country",
        code: "LR",
        // flag: Lr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Libyan Arab Jamahiriya",
        type: "country",
        code: "LY",
        // flag: Ly as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Liechtenstein",
        type: "country",
        code: "LI",
        // flag: Li as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Lithuania",
        type: "country",
        code: "LT",
        // flag: Li as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Luxembourg",
        type: "country",
        code: "LU",
        // flag: Lu as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Macao",
        type: "country",
        code: "MO",
        // flag: Mo as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Macedonia",
        type: "country",
        code: "MK",
        // flag: Mk as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Madagascar",
        type: "country",
        code: "MG",
        // flag: Mg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Malawi",
        type: "country",
        code: "MW",
        // flag: Mw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Malaysia",
        type: "country",
        code: "MY",
        // flag: My as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Maldives",
        type: "country",
        code: "MV",
        // flag: Mv as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Mali",
        type: "country",
        code: "ML",
        // flag: Ml as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Malta",
        type: "country",
        code: "MT",
        // flag: Mt as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Mauritania",
        type: "country",
        code: "MR",
        // flag: Mr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Mauritius",
        type: "country",
        code: "MU",
        // flag: Mu as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Mexico",
        type: "country",
        code: "MX",
        // flag: Mx as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Micronesia",
        type: "country",
        code: "FM",
        // flag: Fm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Moldova",
        type: "country",
        code: "MD",
        // flag: Md as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Monaco",
        type: "country",
        code: "MC",
        // flag: Mc as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Mongolia",
        type: "country",
        code: "MN",
        // flag: Mn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Montenegro",
        type: "country",
        code: "ME",
        // flag: Me as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Montserrat",
        type: "country",
        code: "MS",
        // flag: Ms as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Morocco",
        type: "country",
        code: "MA",
        // flag: Ma as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Mozambique",
        type: "country",
        code: "MZ",
        // flag: Mz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Myanmar",
        type: "country",
        code: "MM",
        // flag: Mm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Namibia",
        type: "country",
        code: "NA",
        // flag: Na as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Nepal",
        type: "country",
        code: "NP",
        // flag: Np as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Netherlands",
        type: "country",
        code: "NL",
        // flag: Nl as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "New Zealand",
        type: "country",
        code: "NZ",
        // flag: Nz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Nicaragua",
        type: "country",
        code: "NI",
        // flag: Ni as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Niger",
        type: "country",
        code: "NE",
        // flag: Ne as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Nigeria",
        type: "country",
        code: "NG",
        // flag: Ng as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Norway",
        type: "country",
        code: "NO",
        // flag: No as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Oman",
        type: "country",
        code: "OM",
        // flag: Om as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Pakistan",
        type: "country",
        code: "PK",
        // flag: Pk as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Palau",
        type: "country",
        code: "PW",
        // flag: Pw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Panama",
        type: "country",
        code: "PA",
        // flag: Pa as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Papua New Guinea",
        type: "country",
        code: "PG",
        // flag: Pg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Paraguay",
        type: "country",
        code: "PY",
        // flag: Py as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Peru",
        type: "country",
        code: "PE",
        // flag: Pe as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Philippines",
        type: "country",
        code: "PH",
        // flag: Ph as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Poland",
        type: "country",
        code: "PL",
        // flag: Pl as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Portugal",
        type: "country",
        code: "PT",
        // flag: Pt as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Puerto Rico",
        type: "country",
        code: "PR",
        // flag: Pr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Qatar",
        type: "country",
        code: "QA",
        // flag: Qa as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Romania",
        type: "country",
        code: "RO",
        // flag: Ro as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Russia",
        type: "country",
        code: "RU",
        // flag: Ru as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Rwanda",
        type: "country",
        code: "RW",
        // flag: Rw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Saint Helena",
        type: "country",
        code: "SH",
        // flag: Sh as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Saint Kitts and Nevis",
        type: "country",
        code: "KN",
        // flag: Kn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Saint Lucia",
        type: "country",
        code: "LC",
        // flag: Lc as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Saint Vincent and the Grenadines",
        type: "country",
        code: "VC",
        // flag: Vc as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Samoa",
        type: "country",
        code: "WS",
        // flag: Ws as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "San Marino",
        type: "country",
        code: "SM",
        // flag: Sm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Sao Tome and Principe",
        type: "country",
        code: "ST",
        // flag: St as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Saudi Arabia",
        type: "country",
        code: "SA",
        // flag: Sa as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Senegal",
        type: "country",
        code: "SN",
        // flag: Sn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Serbia",
        type: "country",
        code: "RS",
        // flag: Rs as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Seychelles",
        type: "country",
        code: "SC",
        // flag: Sc as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Sierra Leone",
        type: "country",
        code: "SL",
        // flag: Sl as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Singapore",
        type: "country",
        code: "SG",
        // flag: Sg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Slovakia",
        type: "country",
        code: "SK",
        // flag: Sk as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Slovenia",
        type: "country",
        code: "SI",
        // flag: Si as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Solomon Islands",
        type: "country",
        code: "SB",
        // flag: Sb as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Somalia",
        type: "country",
        code: "SO",
        // flag: So as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "South Africa",
        type: "country",
        code: "ZA",
        // flag: Za as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Spain",
        type: "country",
        code: "ES",
        // flag: Es as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Sri Lanka",
        type: "country",
        code: "LK",
        // flag: Lk as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Sudan",
        type: "country",
        code: "SD",
        // flag: Sd as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Suriname",
        type: "country",
        code: "SR",
        // flag: Sr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Swaziland",
        type: "country",
        code: "SZ",
        // flag: Sz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Sweden",
        type: "country",
        code: "SE",
        // flag: Se as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Switzerland",
        type: "country",
        code: "CH",
        // flag: Ch as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Syrian Arab Republic",
        type: "country",
        code: "SY",
        // flag: Sy as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Taiwan",
        type: "country",
        code: "TW",
        // flag: Tw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Tajikistan",
        type: "country",
        code: "TJ",
        // flag: Tj as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Tanzania",
        type: "country",
        code: "TZ",
        // flag: Tz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Thailand",
        type: "country",
        code: "TH",
        // flag: Th as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Timor-Leste",
        type: "country",
        code: "TL",
        // flag: Tl as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Togo",
        type: "country",
        code: "TG",
        // flag: Tg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Tonga",
        type: "country",
        code: "TO",
        // flag: To as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Trinidad and Tobago",
        type: "country",
        code: "TT",
        // flag: Tt as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Tunisia",
        type: "country",
        code: "TN",
        // flag: Tn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Turkey",
        type: "country",
        code: "TR",
        // flag: Tr as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Turkmenistan",
        type: "country",
        code: "TM",
        // flag: Tm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Turks and Caicos Islands",
        type: "country",
        code: "TC",
        // flag: Tc as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Uganda",
        type: "country",
        code: "UG",
        // flag: Ug as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Ukraine",
        type: "country",
        code: "UA",
        // flag: Ua as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "United Arab Emirates",
        type: "country",
        code: "AE",
        // flag: Ae as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "United Kingdom",
        type: "country",
        code: "GB",
        // flag: Gb as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "United States",
        type: "country",
        code: "US",
        // flag: Us as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Uruguay",
        type: "country",
        code: "UY",
        // flag: Uy as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Uzbekistan",
        type: "country",
        code: "UZ",
        // flag: Uz as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Vanuatu",
        type: "country",
        code: "VU",
        // flag: Vu as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Venezuela",
        type: "country",
        code: "VE",
        // flag: Ve as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Vietnam",
        type: "country",
        code: "VN",
        // flag: Vn as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Virgin Islands",
        type: "country",
        code: "VG",
        // flag: Vg as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Yemen",
        type: "country",
        code: "YE",
        // flag: Ye as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Zambia",
        type: "country",
        code: "ZM",
        // flag: Zm as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Zimbabwe",
        type: "country",
        code: "ZW",
        // flag: Zw as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "World",
        type: "world",
        code: "WW",
        // flag: Ww as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "North America",
        type: "world",
        code: "CNA",
        // flag: Cna as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "South America",
        type: "world",
        code: "CSA",
        // flag: Csa as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Africa",
        type: "world",
        code: "CAF",
        // flag: Caf as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Europe",
        type: "world",
        code: "CEU",
        // flag: Ceu as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Asia",
        type: "world",
        code: "CAS",
        // flag: Cas as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Oceania",
        type: "world",
        code: "COC",
        // flag: Coc as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "European Union",
        type: "region",
        code: "EU",
        // flag: Eu as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Catolonia",
        type: "region",
        code: "EsCataluna",
        // flag: EsCataluna as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Aragon",
        type: "region",
        code: "EsAragon",
        // flag: EsAragon as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Valencia",
        type: "region",
        code: "EsValencia",
        // flag: EsValencia as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Balearic Islands",
        type: "region",
        code: "ES_BALEAR",
        // flag: EsBalear as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Andalusia",
        type: "region",
        code: "ES_ANDALUCIA",
        // flag: EsAndalucia as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Extremadura",
        type: "region",
        code: "ES_EXTREMADURA",
        // flag: EsExtremadura as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Galicia",
        type: "region",
        code: "ES_GALICIA",
        // flag: EsGalicia as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Navarra",
        type: "region",
        code: "ES_NAVARRA",
        // flag: EsNavarra as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Canary Islands",
        type: "region",
        code: "ES_CANARIAS",
        // flag: EsCanarias as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Madrid",
        type: "region",
        code: "ES_MADRID",
        // flag: EsMadrid as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Asturias",
        type: "region",
        code: "ES_ASTURIAS",
        // flag: EsAsturias as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Basque Country",
        type: "region",
        code: "ES_BASCO",
        // flag: EsBasco as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Rioja",
        type: "region",
        code: "ES_RIOJA",
        // flag: EsRioja as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cantabria",
        type: "region",
        code: "ES_CANTABRIA",
        // flag: EsCantabria as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Castile and León",
        type: "region",
        code: "ES_LEON",
        // flag: EsLeon as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Castile-La Mancha",
        type: "region",
        code: "ES_MANCHA",
        // flag: EsMancha as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Castile-La Mancha",
        type: "region",
        code: "ES_MURCIA",
        // flag: EsMurcia as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Almería",
        type: "city",
        code: "ES_ALMERIA",
        // flag: EsAlmeria as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Barcelona",
        type: "city",
        code: "ES_BARCELONA",
        // flag: EsBarcelona as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Girona",
        type: "city",
        code: "ES_GIRONA",
        // flag: EsGirona as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Tarragona",
        type: "city",
        code: "ES_TARRAGONA",
        // flag: EsTarragona as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Ourense",
        type: "city",
        code: "ES_OURENSE",
        // flag: EsOurense as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Mataró",
        type: "city",
        code: "ES_MATARO",
        // flag: EsMataro as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Cruz de Borgoña",
        type: "historical",
        code: "Es_BORGONA",
        // flag: EsBorgona as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "Republic of Spain",
        type: "historical",
        code: "ES_REPUBLICA",
        // flag: EsRepublica as FC<ComponentProps<"svg"> & SVGRProps>,
    },
    {
        name: "LGTB",
        type: "symbol",
        code: "LGTB",
        // flag: Lgtb as FC<ComponentProps<"svg"> & SVGRProps>,
    },
] as const;

export type FlagsObject = typeof flags;

export type FlagData = FlagsObject[number];

export type FlagCode = FlagsObject[number]["code"];
export type FlagName = FlagsObject[number]["name"];

export type GenericFlagItem = {
    code: FlagCode;
    name: FlagName;
    type: FlagType;
    // flag: FC<ComponentProps<"svg"> & SVGRProps>;
};
